name: McKenzieDrums
favicon: null
layout_spectrum: 0.33402
typography_spectrum: 0.27618
title: A Story of John
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f4f9'
    - '#94c8f1'
    - '#3e3634'
    - '#be6c63'
    - '#e6b098'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
