name: McKenzieDrums
favicon: null
layout_spectrum: 0.04354
typography_spectrum: 0.18087
title: A Story of John
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e6f7d'
    - '#969081'
    - '#18140c'
    - '#abc23a'
    - '#fdfefe'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
