name: McKenzieDrums
favicon: null
layout_spectrum: 0.98125
typography_spectrum: 0.1405842825770378
title: My Grid Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#396b97'
    - '#8f501b'
    - '#f9d5b3'
    - '#d1ab8a'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
