name: McKenzieDrums
favicon: null
layout_spectrum: 0.4689626775216311
typography_spectrum: 0.1405842825770378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9349112114869058
  lightness: 0.5766354890074581
  saturation: 0.014059261186048388
  rhythmicContrast: 0.9575594572816044
purpose: []
